# ============================================================================
# npc_config.yaml
# ----------------------------------------------------------------------------
# Configuration file for NPC AI behavioral tuning and personality adaptation.
# ============================================================================

npc_ai:

  # ───────────────────────────────────────────────────────────────────────────
  # Resource Sensitivity
  # ---------------------------------------------------------------------------
  # When an NPC’s total resources drop below this threshold, they evolve
  # their traits toward survival-focused behavior.
  # ───────────────────────────────────────────────────────────────────────────
  low_resource_threshold: 100


  # ───────────────────────────────────────────────────────────────────────────
  # Trait Adaptation
  # ---------------------------------------------------------------------------
  # Defines how personality traits shift following specific events.
  # Each key maps to a multiplier applied to trait weights.
  # ───────────────────────────────────────────────────────────────────────────
  trait_change:
    win_war: 0.05
    lose_war: 0.05
    low_resources: 0.05
    attacked: 0.05


  # ───────────────────────────────────────────────────────────────────────────
  # Trait Decay
  # ---------------------------------------------------------------------------
  # NPC traits gradually return toward their base personality profile.
  # decay_rate: rate per tick
  # decay_inactive_skip_minutes: skip decay if NPC inactive too long
  # ───────────────────────────────────────────────────────────────────────────
  decay_rate: 0.01
  decay_inactive_skip_minutes: 30


  # ───────────────────────────────────────────────────────────────────────────
  # Espionage Behavior
  # ---------------------------------------------------------------------------
  # Controls AI espionage action logging and visibility.
  #   - espionage_logging: Enable/disable espionage logging entirely
  #   - espionage_log_mode:
  #       all         – log all espionage actions
  #       war_only    – log only actions during active wars
  #       player_only – log only when target is a human player
  # ───────────────────────────────────────────────────────────────────────────
  espionage_logging: true
  espionage_log_mode: "war_only"


  # ───────────────────────────────────────────────────────────────────────────
  # Economic Planning System
  # ---------------------------------------------------------------------------
  # These values define when and how NPCs attempt to stabilize their economy
  # using the global market (Step 5: NPC Economic Planning).
  # NPCs will automatically buy food if starving or sell surplus goods for gold.
  # Adjust these thresholds to control market participation frequency.
  # ───────────────────────────────────────────────────────────────────────────

  # Minimum amount of food an NPC should maintain.
  # If current food < this value, the NPC will attempt to buy food
  # from the global market (if it has enough gold).
  low_food_threshold: 50

  # Minimum gold balance considered “stable.”
  # If gold < this value, the NPC may sell surplus resources (wood, iron, etc.)
  # to restore liquidity before performing other actions.
  low_gold_threshold: 100

  # Defines what “surplus” means for resources.
  # If an NPC has more than this quantity of a non-critical resource,
  # it may sell up to 25% of that resource to the market for gold.
  sell_surplus_threshold: 500
  # ───────────────────────────────────────────────────────────────────────────
  # Debugging and Diagnostics
  # ---------------------------------------------------------------------------
  # Enable detailed economy trace logs for NPC behavior.
  # When true, every trade attempt, skip, and resource check will be logged.
  # When false, only successful or critical events are recorded.
  # ───────────────────────────────────────────────────────────────────────────
  debug_economy: true
