# ============================================================================
# npc_config.yaml
# ----------------------------------------------------------------------------
# Configuration file for NPC AI behavioral tuning and personality adaptation.
# ============================================================================

npc_ai:

  # ───────────────────────────────────────────────────────────────────────────
  # Resource Sensitivity
  # ---------------------------------------------------------------------------
  # When an NPC’s total resources drop below this threshold, they evolve
  # their traits toward survival-focused behavior.
  # ───────────────────────────────────────────────────────────────────────────
  low_resource_threshold: 100


  # ───────────────────────────────────────────────────────────────────────────
  # Trait Adaptation
  # ---------------------------------------------------------------------------
  # Defines how personality traits shift following specific events.
  # Each key maps to a multiplier applied to trait weights.
  # ───────────────────────────────────────────────────────────────────────────
  trait_change:
    win_war: 0.05
    lose_war: 0.05
    low_resources: 0.05
    attacked: 0.05


  # ───────────────────────────────────────────────────────────────────────────
  # Trait Decay
  # ---------------------------------------------------------------------------
  # NPC traits gradually return toward their base personality profile.
  # decay_rate: rate per tick
  # decay_inactive_skip_minutes: skip decay if NPC inactive too long
  # ───────────────────────────────────────────────────────────────────────────
  decay_rate: 0.01
  decay_inactive_skip_minutes: 30


  # ───────────────────────────────────────────────────────────────────────────
  # Espionage Behavior
  # ---------------------------------------------------------------------------
  # Controls AI espionage action logging and visibility.
  #   - espionage_logging: Enable/disable espionage logging entirely
  #   - espionage_log_mode:
  #       all         – log all espionage actions
  #       war_only    – log only actions during active wars
  #       player_only – log only when target is a human player
  # ───────────────────────────────────────────────────────────────────────────
  espionage_logging: true
  espionage_log_mode: "war_only"
