# resources_config.yaml
# Defines all resource types, their starting values, and global market behavior.
# Stone → Bronze Age economy configuration.

resources:
  food:
    description: Edible goods harvested or stored in granaries; essential for survival and trade.
    starting_amount: 100
    base_price: 1.0
    base_supply: 2000

  wood:
    description: Timber gathered from forests; used in tools, housing, and construction.
    starting_amount: 100
    base_price: 1.2
    base_supply: 1500

  stone:
    description: Rough stone quarried for walls, forts, and durable structures.
    starting_amount: 50
    base_price: 1.5
    base_supply: 1000

  copper:
    description: Early metal used for crafting weapons, tools, and trade goods.
    starting_amount: 20
    base_price: 2.0
    base_supply: 800

  gold:
    description: Rare, valuable metal used as primitive currency and prestige.
    starting_amount: 200
    base_price: 3.0
    base_supply: 500

# Global market behavior
market:
  price_floor: 0.5          # Minimum allowed price for any resource
  price_ceiling: 10.0        # Maximum allowed price for any resource
  drift_variance: 0.2        # Random ±20% variation applied each tick
  adjustment_factor: 0.1     # How strongly price responds to supply levels
