Walls:
  description: Increases defending units' defense multiplier.
  cost:
    wood: 100.0
    stone: 60.0
    gold: 40.0
  build_time: 10
  defense_bonus: 0.25
  upkeep:
    gold: 0.2
  role: defence
#Towers:
#  description: Increases defending units' counterattack strength.
#  cost:
#    wood: 75.0
#    stone: 45.0
#    gold: 30.0
#  build_time: 15
#  defense_attack_bonus: 0.15
#  upkeep:
#    gold: 0.2
#  role: defence
Barracks:
  description: Increases the max troops.
  cost:
    wood: 90.0
    stone: 90.0
    gold: 120.0
  build_time: 15
  troop_cap_bonus: 100
  upkeep:
    gold: 0.2
  role: military
Farms:
  description: Increases population growth rate.
  cost:
    wood: 40.0
    stone: 40.0
    gold: 20.0
  build_time: 3
  population_growth_bonus: 1
  upkeep:
    gold: 0.2
  role: growth
Houses:
  description: Increases the max population.
  cost:
    wood: 50.0
    stone: 30.0
    gold: 20.0
  build_time: 3
  max_population_bonus: 50
  upkeep:
    gold: 0.2
  role: growth
Forts:
  description: Increases the attack power of your attacking troops.
  cost:
    wood: 200.0
    stone: 120.0
    gold: 80.0
  build_time: 15
  attack_bonus_per_level: 0.05
  upkeep:
    gold: 0.2
  role: military
Academies:
  cost:
    wood: 200.0
    stone: 120.0
    gold: 80.0
  build_time: 8
  spy_success_bonus: 0.05
  description: Improves espionage training, increasing spy success rate.
  upkeep:
    gold: 0.2
  role: espionage
Watchtowers:
  cost:
    wood: 150.0
    stone: 90.0
    gold: 60.0
  build_time: 6
  spy_defense_bonus: 0.05
  description: Improves counter-intelligence, reducing enemy spy success rate.
  upkeep:
    gold: 0.2
  role: defence
Granaries:
  description: Stores and distributes food, generating food resources each tick.
  cost:
    wood: 20.0
    stone: 12.0
    gold: 15.0
  build_time: 2
  food_per_tick: 2.0
  upkeep:
    gold: 0.2
  role: economy
Lodges:
  description: A simple woodworking structure where settlers gather lumber each tick.
  cost:
    wood: 40.0
    stone: 24.0
    gold: 16.0
  build_time: 3
  wood_per_tick: 6.12
  upkeep:
    gold: 0.2
  role: economy
Quarries:
  description: Extracts rough stone from nearby formations for construction.
  cost:
    wood: 50.0
    stone: 30.0
    gold: 20.0
  build_time: 4
  stone_per_tick: 6.12
  upkeep:
    gold: 0.2
  role: economy
Mines:
  description: A small shaft or pit where early miners collect copper ore.
  cost:
    wood: 45.0
    stone: 75.0
    gold: 30.0
  build_time: 5
  copper_per_tick: 6.12
  upkeep:
    gold: 0.2
  role: economy
Markets:
  description: Central hub for trade and barter, generating gold through commerce.
  cost:
    wood: 40.0
    stone: 60.0
    gold: 100.0
  build_time: 5
  gold_per_tick: 1.09
  upkeep:
    gold: 0.2
  role: economy
