# ============================================================================
# upkeep_config.yaml
# ----------------------------------------------------------------------------
# Configuration for the Upkeep & Consumption System (Step 3)
# Handles per-tick food and gold costs for population, armies, and structures.
# All values can be tuned for balance without code changes.
# ============================================================================

upkeep:

  # ───────────────────────────────────────────────────────────────────────────
  # Food consumption per population unit
  # ---------------------------------------------------------------------------
  # Each citizen consumes this amount of food per tick.
  # If food runs out, the population will decline by STARVATION_LOSS_RATE.
  # Example: With 100 population and 0.5 cost, total food use = 50 food/tick.
  # ───────────────────────────────────────────────────────────────────────────
  food_per_person: 0.02


  # ───────────────────────────────────────────────────────────────────────────
  # Gold cost per soldier
  # ---------------------------------------------------------------------------
  # Each soldier requires this much gold per tick for wages and maintenance.
  # If unpaid, the army will lose units by DESERTION_LOSS_RATE.
  # Example: 200 soldiers × 1.0 = 200 gold per tick.
  # ───────────────────────────────────────────────────────────────────────────
  gold_per_soldier: 0.068


  # ───────────────────────────────────────────────────────────────────────────
  # Starvation loss rate
  # ---------------------------------------------------------------------------
  # Fraction of total population lost when food upkeep fails.
  # Set as a decimal value: 0.05 = 5% of total population lost per tick.
  # Always rounds up to a minimum loss of 1.
  # ───────────────────────────────────────────────────────────────────────────
  starvation_loss_rate: 0.05


  # ───────────────────────────────────────────────────────────────────────────
  # Desertion loss rate
  # ---------------------------------------------------------------------------
  # Fraction of total army size lost when gold upkeep fails.
  # Set as a decimal value: 0.10 = 10% of troops desert each unpaid tick.
  # Always rounds up to a minimum loss of 1.
  # ───────────────────────────────────────────────────────────────────────────
  desertion_loss_rate: 0.10


  # ───────────────────────────────────────────────────────────────────────────
  # Future expansion (optional)
  # ---------------------------------------------------------------------------
  # Reserved for later features:
  # - building_upkeep_gold: Gold upkeep cost per building per tick.
  # - building_upkeep_resource: Optional resource cost per structure type.
  # These can be activated in apply_building_upkeep() when Step 4 begins.
  # ───────────────────────────────────────────────────────────────────────────
  # building_upkeep_gold: 0.2
  # building_upkeep_resource: 0.0
